language: node_js


matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      node_js:
        - "5.9.0"
    - os: osx
      osx_image: xcode7.3
      node_js:
        - "5.9.0"

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

addons:
  apt:
    packages:
      - libnotify4
      - icnsutils
      - graphicsmagick

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
- nvm install 5.9.0
- npm install

script:
- npm run lint
- npm run test-ci
- npm run validate
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run package ; fi
