language: node_js


matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      node_js:
        - "5.9.0"

addons:
  apt:
    packages:
      - libnotify4
      - icnsutils
      - graphicsmagick

install:
- nvm install 5.9.0
- npm install

script:
- npm run lint
- npm run test-ci
- npm run validate
